config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :tweets do
    collection do
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :users, only:[:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' },
  ]
  include ActiveHash::Associations
  has_many :tweets
  end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '球技全般' },
    { id: 3, name: '野球' },
    { id: 4, name: 'サッカー' },
    { id: 5, name: 'バスケットボール' },
    { id: 6, name: 'その他' },
    { id: 7, name: '球技禁止' },
  ]
  include ActiveHash::Associations
  has_many :tweets
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates :text, presence: true
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '広い' },
    { id: 3, name: '普通' },
    { id: 4, name: '狭い' }
  ]
  include ActiveHash::Associations
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments
  with_options presence: true do
    validates :title
    validates :text
    validates :image
  end
  with_options numericality: { other_than: 1 } do
    validates :area_id
    validates :category_id
    validates :status_id
  end
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
  belongs_to :category
  belongs_to :status
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
  validates :user_name, presence: true
  
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze 
  validates :password, format: { with: PASSWORD_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to tweet_path(@comment.tweet)
    else
      @tweet = Tweet.find(params[:tweet_id])
      @comment = Comment.new
      @comments = @tweet.comments.includes(:user)
      render 'tweets/show'
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_q, only: [:index, :search]
  before_action :find, only: [:show, :edit, :update, :destroy, :move_to_index]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweet_path
    else
      render :edit
    end
  end

  def destroy
    if @tweet.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Tweet.ransack(params[:q])
  end


  def tweet_params
    params.require(:tweet).permit(:title, :text, :area_id, :category_id, :status_id, :image).merge(user_id: current_user.id)
  end

  def find
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    if current_user.id != @tweet.user.id
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BallPark3456</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shareds/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shareds/_header.html.erb
<header class='top-page-header'>
  <div class="content">
    <ul class='lists-left'>
      <li><%= link_to 'Ball Seach', root_path, class: "title-list" %></li>
      <li><%= link_to 'New Tweet', new_tweet_path, class: "header-list" %></li>
    </ul>
    <ul class='lists-right'>
    <% if user_signed_in? %>
      <li><%= link_to current_user.user_name, "#", class: "header-list" %> </li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "header-list" %></li>
    <% else %>
      <li><%= link_to 'ログイン', user_session_path, class: "header-list" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "header-list" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/tweets/edit.html.erb
<%= render "shareds/header" %>

<%= form_with(model: @tweet, local: true) do |f| %>
  <h2 class="sinki">ツイートの編集</h2>

  <div class="form-true">

    <div class="form-group">
      <div class="form-text-wrap">
        <label class="form-text" >公園の画像</label>
      </div>
          <%= f.file_field :image, class:"input-text-image", id:"item-image" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >ツイートタイトル</label>
      </div>
      <%= f.text_area :title, class:"input-text-title", autofocus: true, placeholder:"ツイートの題名を入力" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >ツイート</label>
      </div>
      <%= f.text_area :text, class:"input-tweet-text", autofocus: true, placeholder:"ツイートを入力" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >場所</label>
      </div>
      <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-tweet-area", id:"tweet-area"}) %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >遊べるもの</label>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-tweet-category", id:"tweet-category"}) %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >公園の規模</label>
      </div>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-tweet-status", id:"item-sales-status"}) %>
    </div>


    <div class="actions">
      <%= f.submit "変更を更新する", class:"register-red-btn" %>
    </div>
  </div>
<% end %>

app/views/tweets/index.html.erb
<%= render "shareds/header" %>

<div class='main'>
  <div class="setumei">
    <div class="syoukai">
      <%= image_tag "baseball-No.1.jpg", class:"list-pict" %>
    </div>
    <div class="yakyu">
      <h4 class="as">スポーツをしよう！！</h4>
      <div class="yuyu"><li class="intro">公園の写真を投稿しよう！</li>
                      <li class="intro">「ここの公園ボール遊びできない!」</li>
                      <li class="intro">こんな経験ないですか？</li>
                      <li class="intro">こんな時に、「Ball Seach」を使えば</li>
                      <li class="intro">近くの公園の遊べるものがわかります!</li>
                      <li class="intro">遊び終わった後は、写真と一緒に</li>
                      <li class="intro">「New Tweet」から投稿してください！</li>
      </div>
    </div>
  </div>

  <div class="seach-a">
    <div class="seach">
      <%= search_form_for @q, url: search_tweets_path, class:"seach-forms" do |f| %>
        <label class="seach-ob" >検索</label>
        <div class="seach-th">
          <%= f.search_field :title_cont, placeholder:"公園名を入力してください" ,class:"seach-input" %>
          <%= f.submit "検索" , class:"seach-btn" %>
        <div class="seach-th">
      <% end %>
    </div>
  </div>

  <h2 class="sinki">NEW TWEET 一覧表示</h2>

  <ul class="tweet-wrap">
    <% @tweets.each do |tweet|%>
      <li class="tweet-all">
      <%= link_to tweet_path(tweet.id), class:"imag-img" do %>
        <div class='image-content'>
          <%= image_tag tweet.image, class: "tweet-img" %>
        </div>
        <div class='tweet-title'>
          <%= tweet.title %>
        </div>
        <div class='tweet-text'>
          <%= tweet.area.name %>
        </div>
      <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/tweets/new.html.erb
<%= render "shareds/header" %>

<%= form_with model: @tweet, url: tweets_path, class:'form-wrap', local: true do |f| %>
  <h2 class="sinki">NEW TWEET</h2>

  <div class="form-group">
    <div class='form-text-wrap'>
      <%= render 'shareds/error_messages', model: f.object %>
    </div>
  </div>


  <div class="form-true">

    <div class="form-group">
      <div class="form-text-wrap">
        <label class="form-text" >公園の画像</label>
      </div>
          <%= f.file_field :image, class:"input-text-image", id:"item-image" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >ツイートタイトル</label>
      </div>
      <%= f.text_area :title, class:"input-text-title", autofocus: true, placeholder:"ツイートの題名を入力" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >ツイート</label>
      </div>
      <%= f.text_area :text, class:"input-tweet-text", autofocus: true, placeholder:"ツイートを入力" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >場所</label>
      </div>
      <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-tweet-area", id:"tweet-area"}) %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >遊べるもの</label>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-tweet-category", id:"tweet-category"}) %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text" >公園の規模</label>
      </div>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-tweet-status", id:"item-sales-status"}) %>
    </div>


    <div class="actions">
      <%= f.submit "ツイートする" ,class:"register-red-btn" %>
    </div>
  </div>
<% end %>

app/views/tweets/search.html.erb
<%= render "shareds/header" %>

<h2 class="sinki-a">検索結果表示</h2>

<ul class="tweet-wrap">
  <% @results.each do |tweet| %>
    <li class="tweet-all">
      <%= link_to tweet_path(tweet.id), class:"imag-img" do %>
        <div class='image-content'>
          <%= image_tag tweet.image, class: "tweet-img" %>
        </div>
        <div class='tweet-title'>
          <%= tweet.title %>
        </div>
        <div class='tweet-text'>
          <%= tweet.area.name %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tweets/show.html.erb
<%= render "shareds/header" %>

<h2 class="sinki">TWEETの詳細</h2>

<div class="main-show">
  <%= link_to ("投稿者 #{@tweet.user.user_name} さん"), user_path(@tweet.user.id), class: :tweet_user %>
  <% if user_signed_in? && current_user.id == @tweet.user_id %>
    <div class="tweet__manage">
      <%= link_to "編集する", edit_tweet_path(@tweet.id), class: :tweet_edit_btn %>
      <%= link_to "削除する", tweet_path(@tweet.id), method: :delete, class: :tweet_delete_btn %>
    </div>
  <% end %>
  <div class='image-content-show'>
    <%= image_tag @tweet.image, class: "tweet-img-show" %>
  </div>
  <div class='show-tweet-show'>
    <%= @tweet.title %>
  </div>
  <h2 class="sinki">公園の紹介</h2>
  <div class='show-tweet-text'>
    <%= @tweet.text %>
  </div>
  <table class="show-table">
    <tbody>
      <tr>
        <th class="show-area">地域</th>
        <td class="show-value"><%= @tweet.area.name %></td>
      </tr>
      <tr>
        <th class="show-area">遊べるもの</th>
        <td class="show-value"><%= @tweet.category.name %></td>
      </tr>
      <tr>
        <th class="show-area">公園の規模</th>
        <td class="show-value"><%= @tweet.status.name %></td>
      </tr>
    </tbody>
  </table>

  <div class="tweet-commets">
    <% if user_signed_in? %>
      <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
        <div class="field">
          <%= f.label :comments, "コメント入力" %><br />
          <%= f.text_field :text, class:"comment-form" %><%= f.submit "送信する", class: :form_btn  %>
        </div>
        <div class="actions">
        </div>
      <% end %>
    <% end %>
    <ul class="comment-lists">
      <li class="itiran">コメント一覧</li>
    <% @comments.reverse.each do |comment| %>
      <div class="comments_lists">
        <li class="comments_list">
          ■<p><%= comment.text %></p><%= time_ago_in_words(comment.created_at) + "前" %>
        </li>
        <li class="comments_user">
          投稿者<p><%= comment.user.user_name %></p>さん
        </li>
      </div>
    <% end %>
    </ul>
  </div>
</div>

app/views/users/_tweet.html.erb
<div class="card">
  <div class='image-content'>
    <%= link_to image_tag(tweet.image, class: :card_img ), tweet_path(tweet.id) %>
  </div>
  <div class='tweet-title'>
    <%= tweet.title %>
  </div>
  <div class='card_summary'>
    <%= tweet.area.name %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shareds/header" %>

<h2 class="sinki"><%= @user.user_name%>さんの投稿</h2>


<div class="user-tweet">
  <%= render partial: "tweet", collection: @user.tweets %>
</div>